# Generated by Django 4.2.2 on 2023-06-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
